# Generated by Django 4.2 on 2023-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_cd', '0003_alter_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='dofu_file/'),
        ),
    ]
