# Generated by Django 4.2 on 2023-07-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
