# Generated by Django 4.2 on 2023-07-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roll_cd', '0002_alter_song_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
