# Generated by Django 4.2 on 2023-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs_0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, unique=True)),
                ('song_file', models.FileField(upload_to='song_files/')),
            ],
        ),
    ]
